### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by malaespera** [venice1200/MiSTer_i2c2oled#3]
Modify update_i2c2oled.sh so that the content is updated through the update_all script.

**Comment by venice1200** [comment]
This was requested by us but not added by the maintainer of update_all.
update_ all is just downloading the i2c2oled update file but doesn‘t start it.
But it‘s easy to start update_i2c2oled through the MiSTer’s Script Menu.

The same for update_tty2oled.

Thanks for your request but I can’t help here.

**Comment by malaespera** [comment]
I have spoken with JoseBG who is the coder of update_all and he told me: The i2c2oled coder could improve the distribution so that it is integrated into the downloader, in that case it would not be necessary to run a separate script. But that's up to him, not me. You can ask him.

**Comment by venice1200** [comment]
update_all is just a downloader and is loading everything you configure.
You have to add every file you like to be loaded to the update_all config which makes it too complicate as we have more than 600 Pictures to manage. 

Our updater does this automatically using rsync from our own repository and we are happy with this.

**Comment by malaespera** [comment]
Ok thank you.
